version: '3.4'

volumes:
  ui-node_modules:
  api:

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        mail:8025
        bajads:ui:5173
        sql:adminer:8080
    ports:
    - 80

  ui:
    build:
      context: .
      target: ui-dev
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: "true"
      NODE_ENV: development
    volumes:
    - ./vue:/app
    - ui-node_modules:/app/node_modules
    depends_on:
    - gw

  api:
    build:
      context: .
      target: dev
      dockerfile: docker/Dockerfile
    environment:
      DB_DSN: postgres://bruger:kodeord@db/productcatalog?sslmode=disable
      SMS_DSN: cpsms://TOKEN@api.cpsms.dk
      SMTP_HOST: mail
      SMTP_PORT: 1025
    volumes:
    - .:/app
    - api:/go

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bruger
      POSTGRES_PASSWORD: kodeord
      POSTGRES_DB: productcatalog

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db

  mail:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    restart: unless-stopped
